name: hunter_final
description: Packages for our enhanced features
version: 0.0.1-pre

environment:
 sdk: ^3.6.0

# Dependencies are added in sections alphabetically and according to features.
dependencies:
 flutter:
   sdk: flutter
